# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('circuit', models.CharField(max_length=2500)),
            ],
        ),
    ]
