# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('levels', '0002_remove_levels_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.CharField(max_length=10000)),
                ('parts', models.CharField(max_length=5000)),
                ('labels', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='levels',
            name='circuit',
            field=models.CharField(max_length=10000),
        ),
    ]
